### ISSUE TITLE
Control pop-up is black on dark grey with ElementaryOS theme

### ISSUE THREAD

**Issue by ineuw** [collinss/Cinnamon-Sticky-Notes#10]
It's not possible to see the hide and add controls with the ElementaryOS theme, which is my preference. Can you please advise how can the CSS be modified to correct this?

As a suggestion, would it be possible to add the add + hide control on the notes itself?

Thanks

**Comment by collinss** [comment]
Are you using the version here on github, or are you using the one from the spices website? I'm guessing it's the spices version since you only mentioned 'add' and 'hide'. The github version is much more up to date, and likely wont have that issue as the menu was redesigned a while back. I keep meaning to push the new version to the spices website, but I never got around to it, there always seems to be one more issue I want to iron out before I do.

**Comment by ineuw** [comment]
Hi, you were correct. The previous was from the spices, so I downloaded your current version and it works fine. Just to note, the files downloaded from your Github page are packaged as 'Cinnamon-Sticky-Notes-master', and I wasn't sure if it was supposed to be like that, so I deleted the old contents of the 'sticky@scollins' and moved the master contents into that empty folder. Would it be a problem, if I would have left the folder name as 'Cinnamon-Sticky-Notes-master' or only the .local/share/cinnamon/applets  folder is important? Just trying to learn Mint's organization which is different (and better) than Xubuntu.

**Comment by collinss** [comment]
What you did is correct. I believe the 'Cinnamon-Sticky-Notes-master' folder is just the name that github gave it when you downloaded it. In any case, .local/share/cinnamon/applets/sticky@scollins is the correct location.

Since it worked for you, I'm going to go ahead and close this now.
